<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="16" hostname="Ayesha-laptop" failures="15" tests="48" name="TestAPIs Sequential Execution" time="9.578" errors="0" timestamp="2025-08-04T10:53:16 PKT">
  <testcase classname="TestAPIs.ActionsAPITest" name="TC01_CreateAction" time="2.608"/>
  <testcase classname="TestAPIs.ActionsAPITest" name="TC01_CreateAction" time="0.058"/>
  <testcase classname="TestAPIs.ActionsAPITest" name="TC02_GetAction" time="0.173"/>
  <testcase classname="TestAPIs.ActionsAPITest" name="TC03_UpdateActionByID" time="0.089"/>
  <testcase classname="TestAPIs.ActionsAPITest" name="TC04_GetActionByID" time="0.045"/>
  <testcase classname="TestAPIs.ActionsAPITest" name="TC05_DeleteActionByID" time="0.083">
    <failure type="java.lang.AssertionError" message="expected [success] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [success] but found [null]
at TestAPIs.ActionsAPITest.TC05_DeleteActionByID(ActionsAPITest.java:161)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TC05_DeleteActionByID -->
  <testcase classname="TestAPIs.GetPermissionsTests" name="TC01_GetPermissions_ValidToken" time="0.329"/>
  <testcase classname="TestAPIs.GetPermissionsTests" name="TC02_GetPermissions_InvalidTokens" time="0.036"/>
  <testcase classname="TestAPIs.GetPermissionsTests" name="TC02_GetPermissions_InvalidTokens" time="0.055"/>
  <testcase classname="TestAPIs.GetPermissionsTests" name="TC02_GetPermissions_InvalidTokens" time="0.041"/>
  <testcase classname="TestAPIs.GetPermissionsTests" name="TC07_GetPermissions_ResponseTimeCheck" time="0.291"/>
  <testcase classname="TestAPIs.LoginTest" name="testLogin" time="0.169"/>
  <testcase classname="TestAPIs.LoginTest" name="testLogin" time="0.175"/>
  <testcase classname="TestAPIs.LoginTest" name="testLogin" time="0.047"/>
  <testcase classname="TestAPIs.LoginTest" name="testLogin" time="0.067"/>
  <testcase classname="TestAPIs.LoginTest" name="testLogin" time="0.047"/>
  <testcase classname="TestAPIs.LogoutTest" name="TC01_Logout_ValidToken" time="0.26"/>
  <testcase classname="TestAPIs.ModuleAPITest" name="TC01_CreateModule" time="0.106">
    <failure type="java.lang.AssertionError" message="expected [success] but found [error]">
      <![CDATA[java.lang.AssertionError: expected [success] but found [error]
at TestAPIs.ModuleAPITest.TC01_CreateModule(ModuleAPITest.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TC01_CreateModule -->
  <testcase classname="TestAPIs.ModuleAPITest" name="TC01_CreateModule" time="0.066"/>
  <testcase classname="TestAPIs.ModuleAPITest" name="TC02_GetModule" time="0.184"/>
  <testcase classname="TestAPIs.ModuleAPITest" name="TC03_GetModuleByID" time="0.053">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;pojo.module.ModuleData.getName()&amp;quot; because the return value of &amp;quot;pojo.module.ModuleListDataById.getModule()&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "pojo.module.ModuleData.getName()" because the return value of "pojo.module.ModuleListDataById.getModule()" is null
at TestAPIs.ModuleAPITest.TC03_GetModuleByID(ModuleAPITest.java:116)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TC03_GetModuleByID -->
  <testcase classname="TestAPIs.ModuleAPITest" name="TC04_DeleteModuleByID" time="0.056">
    <failure type="java.lang.AssertionError" message="expected [success] but found [error]">
      <![CDATA[java.lang.AssertionError: expected [success] but found [error]
at TestAPIs.ModuleAPITest.TC04_DeleteModuleByID(ModuleAPITest.java:132)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TC04_DeleteModuleByID -->
  <testcase classname="TestAPIs.PagesAPITest" name="TC01_CreatePage" time="0.081"/>
  <testcase classname="TestAPIs.PagesAPITest" name="TC01_CreatePage" time="0.046"/>
  <testcase classname="TestAPIs.PagesAPITest" name="TC01_CreatePage" time="0.059">
    <failure type="java.lang.AssertionError" message="expected [Parent is not exists with given ID] but found [Path already exists]">
      <![CDATA[java.lang.AssertionError: expected [Parent is not exists with given ID] but found [Path already exists]
at TestAPIs.PagesAPITest.TC01_CreatePage(PagesAPITest.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TC01_CreatePage -->
  <testcase classname="TestAPIs.PagesAPITest" name="TC02_GetPage" time="0.167"/>
  <testcase classname="TestAPIs.PagesAPITest" name="TC03_GetPageByID" time="0.06"/>
  <testcase classname="TestAPIs.PagesAPITest" name="TC04_DeletePageByID" time="0.062"/>
  <testcase classname="TestAPIs.ResetPasswordTest" name="TC01_ResetPassword_correctPassword" time="1.364"/>
  <testcase classname="TestAPIs.ResetPasswordTest" name="TC01_ResetPassword_correctPassword" time="0.239"/>
  <testcase classname="TestAPIs.ResetPasswordTest" name="TC01_ResetPassword_correctPassword" time="0.333"/>
  <testcase classname="TestAPIs.RoleAPITest" name="TC01_CreateRole" time="0.252">
    <failure type="java.lang.AssertionError" message="expected [success] but found [error]">
      <![CDATA[java.lang.AssertionError: expected [success] but found [error]
at TestAPIs.RoleAPITest.TC01_CreateRole(RoleAPITest.java:116)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TC01_CreateRole -->
  <testcase classname="TestAPIs.RoleAPITest" name="TC01_CreateRole" time="0.14"/>
  <testcase classname="TestAPIs.RoleAPITest" name="TC01_CreateRole" time="0.13"/>
  <testcase classname="TestAPIs.RoleAPITest" name="TC01_CreateRole" time="0.17"/>
  <testcase classname="TestAPIs.RoleAPITest" name="TC01_CreateRole" time="0.17"/>
  <testcase classname="TestAPIs.RoleAPITest" name="TC02_GetRole" time="0.21">
    <failure type="java.lang.AssertionError" message="Role name mismatch expected [TestRole213] but found [TestRole1]">
      <![CDATA[java.lang.AssertionError: Role name mismatch expected [TestRole213] but found [TestRole1]
at TestAPIs.RoleAPITest.TC02_GetRole(RoleAPITest.java:146)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- TC02_GetRole -->
  <testcase classname="TestAPIs.RoleAPITest" name="TC03_GetROleByID" time="0.06">
    <failure type="java.lang.AssertionError" message="expected [Role retrieved successfully by ID] but found [Role not found]">
      <![CDATA[java.lang.AssertionError: expected [Role retrieved successfully by ID] but found [Role not found]
at TestAPIs.RoleAPITest.TC03_GetROleByID(RoleAPITest.java:177)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TC03_GetROleByID -->
  <testcase classname="TestAPIs.RoleAPITest" name="TC04_DeleteRoleByID" time="0.046">
    <failure type="java.lang.AssertionError" message="expected [success] but found [error]">
      <![CDATA[java.lang.AssertionError: expected [success] but found [error]
at TestAPIs.RoleAPITest.TC04_DeleteRoleByID(RoleAPITest.java:197)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TC04_DeleteRoleByID -->
  <testcase classname="TestAPIs.UsersAPITest" name="TC01_CreateUser" time="0.065">
    <failure type="java.lang.AssertionError" message="expected [Successfully Created] but found [User Already exist!]">
      <![CDATA[java.lang.AssertionError: expected [Successfully Created] but found [User Already exist!]
at TestAPIs.UsersAPITest.TC01_CreateUser(UsersAPITest.java:74)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TC01_CreateUser -->
  <testcase classname="TestAPIs.UsersAPITest" name="TC01_CreateUser" time="0.044"/>
  <testcase classname="TestAPIs.UsersAPITest" name="TC01_CreateUser" time="0.041"/>
  <testcase classname="TestAPIs.UsersAPITest" name="TC01_CreateUser" time="0.165">
    <failure type="java.lang.AssertionError" message="expected [400] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [0]
at TestAPIs.UsersAPITest.TC01_CreateUser(UsersAPITest.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- TC01_CreateUser -->
  <testcase classname="TestAPIs.UsersAPITest" name="TC01_CreateUser" time="0.057"/>
  <testcase classname="TestAPIs.UsersAPITest" name="TC01_CreateUser" time="0.154">
    <failure type="java.lang.AssertionError" message="expected [400] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [0]
at TestAPIs.UsersAPITest.TC01_CreateUser(UsersAPITest.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- TC01_CreateUser -->
  <testcase classname="TestAPIs.UsersAPITest" name="TC02_GetUser" time="0.107">
    <failure type="java.lang.AssertionError" message="User not found with email: testing@m3tech.com.pk expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: User not found with email: testing@m3tech.com.pk expected [true] but found [false]
at TestAPIs.UsersAPITest.TC02_GetUser(UsersAPITest.java:129)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- TC02_GetUser -->
  <testcase classname="TestAPIs.UsersAPITest" name="TC03_GetUserByID" time="0.046">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;pojo.user.UserData.getEmail()&amp;quot; because the return value of &amp;quot;pojo.user.UserListDataByID.getUser()&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "pojo.user.UserData.getEmail()" because the return value of "pojo.user.UserListDataByID.getUser()" is null
at TestAPIs.UsersAPITest.TC03_GetUserByID(UsersAPITest.java:151)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TC03_GetUserByID -->
  <testcase classname="TestAPIs.UsersAPITest" name="TC04_DeleteUserByID" time="0.062">
    <failure type="java.lang.AssertionError" message="expected [success] but found [error]">
      <![CDATA[java.lang.AssertionError: expected [success] but found [error]
at TestAPIs.UsersAPITest.TC04_DeleteUserByID(UsersAPITest.java:171)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TC04_DeleteUserByID -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setupExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupExtentReport -->
  <testcase classname="base.BaseTest" name="@AfterSuite tearDownReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownReport -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setupExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupExtentReport -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setupExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupExtentReport -->
  <testcase classname="base.BaseTest" name="@AfterSuite tearDownReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownReport -->
  <testcase classname="base.BaseTest" name="@AfterSuite tearDownReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownReport -->
  <testcase classname="base.BaseTest" name="@AfterSuite tearDownReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownReport -->
  <testcase classname="base.BaseTest" name="@AfterSuite tearDownReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownReport -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setupExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupExtentReport -->
  <testcase classname="base.BaseTest" name="@AfterSuite tearDownReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownReport -->
  <testcase classname="base.BaseTest" name="@AfterSuite tearDownReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownReport -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setupExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupExtentReport -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setupExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupExtentReport -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setupExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupExtentReport -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setupExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupExtentReport -->
  <testcase classname="base.BaseTest" name="@AfterSuite tearDownReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownReport -->
</testsuite> <!-- TestAPIs Sequential Execution -->
