<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="48" passed="33" failed="15" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-08-04T10:53:07 PKT" name="API Test Suite" finished-at="2025-08-04T10:53:16 PKT" duration-ms="9578">
    <groups>
    </groups>
    <test started-at="2025-08-04T10:53:07 PKT" name="TestAPIs Sequential Execution" finished-at="2025-08-04T10:53:16 PKT" duration-ms="9578">
      <class name="TestAPIs.LogoutTest">
        <test-method signature="TC01_Logout_ValidToken()[pri:0, instance:TestAPIs.LogoutTest@798162bc]" started-at="2025-08-04T10:53:11 PKT" name="TC01_Logout_ValidToken" finished-at="2025-08-04T10:53:11 PKT" duration-ms="260" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_Logout_ValidToken -->
      </class> <!-- TestAPIs.LogoutTest -->
      <class name="TestAPIs.ResetPasswordTest">
        <test-method signature="TC01_ResetPassword_correctPassword(java.lang.String,java.lang.String,int,java.lang.String)[pri:0, instance:TestAPIs.ResetPasswordTest@7486b455]" started-at="2025-08-04T10:53:12 PKT" name="TC01_ResetPassword_correctPassword" data-provider="resetPasswordScenarios" finished-at="2025-08-04T10:53:14 PKT" duration-ms="1364" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[superAdmin123@]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[superAdmin123@@]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Password updated successfully]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_ResetPassword_correctPassword -->
        <test-method signature="TC01_ResetPassword_correctPassword(java.lang.String,java.lang.String,int,java.lang.String)[pri:0, instance:TestAPIs.ResetPasswordTest@7486b455]" started-at="2025-08-04T10:53:14 PKT" name="TC01_ResetPassword_correctPassword" data-provider="resetPasswordScenarios" finished-at="2025-08-04T10:53:14 PKT" duration-ms="239" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[wrongpass]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[superAdmin123@@]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[400]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Current password is incorrect]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_ResetPassword_correctPassword -->
        <test-method signature="TC01_ResetPassword_correctPassword(java.lang.String,java.lang.String,int,java.lang.String)[pri:0, instance:TestAPIs.ResetPasswordTest@7486b455]" started-at="2025-08-04T10:53:14 PKT" name="TC01_ResetPassword_correctPassword" data-provider="resetPasswordScenarios" finished-at="2025-08-04T10:53:14 PKT" duration-ms="333" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[superAdmin123@@]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[superAdmin123@]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Password updated successfully]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_ResetPassword_correctPassword -->
      </class> <!-- TestAPIs.ResetPasswordTest -->
      <class name="TestAPIs.ActionsAPITest">
        <test-method is-config="true" signature="setupExtentReport()[pri:0, instance:TestAPIs.ActionsAPITest@4c39bec8]" started-at="2025-08-04T10:53:06 PKT" name="setupExtentReport" finished-at="2025-08-04T10:53:07 PKT" duration-ms="225" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupExtentReport -->
        <test-method signature="TC01_CreateAction(java.lang.String,java.lang.String,int,java.lang.String)[pri:1, instance:TestAPIs.ActionsAPITest@4c39bec8]" started-at="2025-08-04T10:53:07 PKT" name="TC01_CreateAction" data-provider="createActionData" finished-at="2025-08-04T10:53:09 PKT" duration-ms="2608" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Add_Action]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[success]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Successfully Created]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreateAction -->
        <test-method signature="TC01_CreateAction(java.lang.String,java.lang.String,int,java.lang.String)[pri:1, instance:TestAPIs.ActionsAPITest@4c39bec8]" started-at="2025-08-04T10:53:09 PKT" name="TC01_CreateAction" data-provider="createActionData" finished-at="2025-08-04T10:53:09 PKT" duration-ms="58" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Add_Action]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[error]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[403]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Action Already exists!]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreateAction -->
        <test-method signature="TC02_GetAction()[pri:2, instance:TestAPIs.ActionsAPITest@4c39bec8]" started-at="2025-08-04T10:53:09 PKT" name="TC02_GetAction" finished-at="2025-08-04T10:53:10 PKT" duration-ms="173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_GetAction -->
        <test-method signature="TC03_UpdateActionByID()[pri:3, instance:TestAPIs.ActionsAPITest@4c39bec8]" started-at="2025-08-04T10:53:10 PKT" name="TC03_UpdateActionByID" finished-at="2025-08-04T10:53:10 PKT" duration-ms="89" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03_UpdateActionByID -->
        <test-method signature="TC04_GetActionByID()[pri:4, instance:TestAPIs.ActionsAPITest@4c39bec8]" started-at="2025-08-04T10:53:10 PKT" name="TC04_GetActionByID" finished-at="2025-08-04T10:53:10 PKT" duration-ms="45" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC04_GetActionByID -->
        <test-method signature="TC05_DeleteActionByID()[pri:5, instance:TestAPIs.ActionsAPITest@4c39bec8]" started-at="2025-08-04T10:53:10 PKT" name="TC05_DeleteActionByID" finished-at="2025-08-04T10:53:10 PKT" duration-ms="83" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [success] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [success] but found [null]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at TestAPIs.ActionsAPITest.TC05_DeleteActionByID(ActionsAPITest.java:161)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC05_DeleteActionByID -->
        <test-method is-config="true" signature="tearDownReport()[pri:0, instance:TestAPIs.ActionsAPITest@4c39bec8]" started-at="2025-08-04T10:53:16 PKT" name="tearDownReport" finished-at="2025-08-04T10:53:17 PKT" duration-ms="325" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownReport -->
      </class> <!-- TestAPIs.ActionsAPITest -->
      <class name="TestAPIs.ModuleAPITest">
        <test-method signature="TC01_CreateModule(java.lang.String,java.lang.String,java.lang.String,java.lang.String,int,java.lang.String)[pri:1, instance:TestAPIs.ModuleAPITest@1df8da7a]" started-at="2025-08-04T10:53:11 PKT" name="TC01_CreateModule" data-provider="createModuleData" finished-at="2025-08-04T10:53:11 PKT" duration-ms="106" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[TestModule1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/testAuto]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ri:icon]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[success]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[Successfully Created]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [success] but found [error]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [success] but found [error]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at TestAPIs.ModuleAPITest.TC01_CreateModule(ModuleAPITest.java:61)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreateModule -->
        <test-method signature="TC01_CreateModule(java.lang.String,java.lang.String,java.lang.String,java.lang.String,int,java.lang.String)[pri:1, instance:TestAPIs.ModuleAPITest@1df8da7a]" started-at="2025-08-04T10:53:11 PKT" name="TC01_CreateModule" data-provider="createModuleData" finished-at="2025-08-04T10:53:11 PKT" duration-ms="66" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[TestModule1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/testAuto]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ri:icon]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[error]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[400]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[Module already exists]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreateModule -->
        <test-method signature="TC02_GetModule()[pri:2, instance:TestAPIs.ModuleAPITest@1df8da7a]" started-at="2025-08-04T10:53:11 PKT" name="TC02_GetModule" finished-at="2025-08-04T10:53:12 PKT" duration-ms="184" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_GetModule -->
        <test-method signature="TC03_GetModuleByID()[pri:3, instance:TestAPIs.ModuleAPITest@1df8da7a]" started-at="2025-08-04T10:53:12 PKT" name="TC03_GetModuleByID" finished-at="2025-08-04T10:53:12 PKT" duration-ms="53" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "pojo.module.ModuleData.getName()" because the return value of "pojo.module.ModuleListDataById.getModule()" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "pojo.module.ModuleData.getName()" because the return value of "pojo.module.ModuleListDataById.getModule()" is null
at TestAPIs.ModuleAPITest.TC03_GetModuleByID(ModuleAPITest.java:116)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03_GetModuleByID -->
        <test-method signature="TC04_DeleteModuleByID()[pri:4, instance:TestAPIs.ModuleAPITest@1df8da7a]" started-at="2025-08-04T10:53:12 PKT" name="TC04_DeleteModuleByID" finished-at="2025-08-04T10:53:12 PKT" duration-ms="56" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [success] but found [error]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [success] but found [error]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at TestAPIs.ModuleAPITest.TC04_DeleteModuleByID(ModuleAPITest.java:132)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC04_DeleteModuleByID -->
      </class> <!-- TestAPIs.ModuleAPITest -->
      <class name="TestAPIs.GetPermissionsTests">
        <test-method signature="TC01_GetPermissions_ValidToken()[pri:1, instance:TestAPIs.GetPermissionsTests@26b3fd41]" started-at="2025-08-04T10:53:10 PKT" name="TC01_GetPermissions_ValidToken" finished-at="2025-08-04T10:53:10 PKT" duration-ms="329" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_GetPermissions_ValidToken -->
        <test-method signature="TC02_GetPermissions_InvalidTokens(java.lang.String)[pri:2, instance:TestAPIs.GetPermissionsTests@26b3fd41]" started-at="2025-08-04T10:53:10 PKT" name="TC02_GetPermissions_InvalidTokens" data-provider="invalidTokens" finished-at="2025-08-04T10:53:10 PKT" duration-ms="36" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Bearer invalid-token]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_GetPermissions_InvalidTokens -->
        <test-method signature="TC02_GetPermissions_InvalidTokens(java.lang.String)[pri:2, instance:TestAPIs.GetPermissionsTests@26b3fd41]" started-at="2025-08-04T10:53:10 PKT" name="TC02_GetPermissions_InvalidTokens" data-provider="invalidTokens" finished-at="2025-08-04T10:53:10 PKT" duration-ms="55" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Bearer ]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_GetPermissions_InvalidTokens -->
        <test-method signature="TC02_GetPermissions_InvalidTokens(java.lang.String)[pri:2, instance:TestAPIs.GetPermissionsTests@26b3fd41]" started-at="2025-08-04T10:53:10 PKT" name="TC02_GetPermissions_InvalidTokens" data-provider="invalidTokens" finished-at="2025-08-04T10:53:10 PKT" duration-ms="41" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_GetPermissions_InvalidTokens -->
        <test-method signature="TC07_GetPermissions_ResponseTimeCheck()[pri:4, instance:TestAPIs.GetPermissionsTests@26b3fd41]" started-at="2025-08-04T10:53:10 PKT" name="TC07_GetPermissions_ResponseTimeCheck" finished-at="2025-08-04T10:53:11 PKT" duration-ms="291" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC07_GetPermissions_ResponseTimeCheck -->
      </class> <!-- TestAPIs.GetPermissionsTests -->
      <class name="TestAPIs.RoleAPITest">
        <test-method signature="TC01_CreateRole(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,int,java.lang.String)[pri:1, instance:TestAPIs.RoleAPITest@660acfb]" started-at="2025-08-04T10:53:14 PKT" name="TC01_CreateRole" data-provider="createRoleData" finished-at="2025-08-04T10:53:14 PKT" duration-ms="252" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Valid Role Creation]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[TestRole213]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Mid Access Tesing Role213]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[User]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[success]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Role Created Successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [success] but found [error]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [success] but found [error]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at TestAPIs.RoleAPITest.TC01_CreateRole(RoleAPITest.java:116)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreateRole -->
        <test-method signature="TC01_CreateRole(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,int,java.lang.String)[pri:1, instance:TestAPIs.RoleAPITest@660acfb]" started-at="2025-08-04T10:53:14 PKT" name="TC01_CreateRole" data-provider="createRoleData" finished-at="2025-08-04T10:53:15 PKT" duration-ms="140" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Duplicate Role Name]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[TestRole213]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Mid Access Tesing Role213]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[User]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[error]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[403]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Role already exists!]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreateRole -->
        <test-method signature="TC01_CreateRole(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,int,java.lang.String)[pri:1, instance:TestAPIs.RoleAPITest@660acfb]" started-at="2025-08-04T10:53:15 PKT" name="TC01_CreateRole" data-provider="createRoleData" finished-at="2025-08-04T10:53:15 PKT" duration-ms="130" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Invalid Page ID]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[TestRoleDummy213]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Mid Access Tesing Role213]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[User]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[error]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[403]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Requested Page(s) does not exist]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreateRole -->
        <test-method signature="TC01_CreateRole(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,int,java.lang.String)[pri:1, instance:TestAPIs.RoleAPITest@660acfb]" started-at="2025-08-04T10:53:15 PKT" name="TC01_CreateRole" data-provider="createRoleData" finished-at="2025-08-04T10:53:15 PKT" duration-ms="170" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Invalid Action Id]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[TestRoleDummy213]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Mid Access Tesing Role213]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[User]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[error]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[403]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Requested Action(s) does not exist.]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreateRole -->
        <test-method signature="TC01_CreateRole(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,int,java.lang.String)[pri:1, instance:TestAPIs.RoleAPITest@660acfb]" started-at="2025-08-04T10:53:15 PKT" name="TC01_CreateRole" data-provider="createRoleData" finished-at="2025-08-04T10:53:15 PKT" duration-ms="170" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Invalid Type]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[TestRoleDummy213]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Mid Access Tesing Role213]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[TestUser]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[error]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[400]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Invalid body]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreateRole -->
        <test-method signature="TC02_GetRole()[pri:2, instance:TestAPIs.RoleAPITest@660acfb]" started-at="2025-08-04T10:53:15 PKT" name="TC02_GetRole" finished-at="2025-08-04T10:53:15 PKT" duration-ms="210" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Role name mismatch expected [TestRole213] but found [TestRole1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Role name mismatch expected [TestRole213] but found [TestRole1]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at TestAPIs.RoleAPITest.TC02_GetRole(RoleAPITest.java:146)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_GetRole -->
        <test-method signature="TC03_GetROleByID()[pri:3, instance:TestAPIs.RoleAPITest@660acfb]" started-at="2025-08-04T10:53:15 PKT" name="TC03_GetROleByID" finished-at="2025-08-04T10:53:15 PKT" duration-ms="60" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Role retrieved successfully by ID] but found [Role not found]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Role retrieved successfully by ID] but found [Role not found]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at TestAPIs.RoleAPITest.TC03_GetROleByID(RoleAPITest.java:177)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03_GetROleByID -->
        <test-method signature="TC04_DeleteRoleByID()[pri:4, instance:TestAPIs.RoleAPITest@660acfb]" started-at="2025-08-04T10:53:15 PKT" name="TC04_DeleteRoleByID" finished-at="2025-08-04T10:53:15 PKT" duration-ms="46" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [success] but found [error]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [success] but found [error]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at TestAPIs.RoleAPITest.TC04_DeleteRoleByID(RoleAPITest.java:197)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC04_DeleteRoleByID -->
      </class> <!-- TestAPIs.RoleAPITest -->
      <class name="TestAPIs.PagesAPITest">
        <test-method signature="TC01_CreatePage(java.lang.String,java.lang.String,java.lang.String,int,java.lang.String,int,java.lang.String)[pri:1, instance:TestAPIs.PagesAPITest@23941fb4]" started-at="2025-08-04T10:53:12 PKT" name="TC01_CreatePage" data-provider="createPageData" finished-at="2025-08-04T10:53:12 PKT" duration-ms="81" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[TestModule1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/testAuto]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ri:icon]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[26]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[success]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Successfully Created]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreatePage -->
        <test-method signature="TC01_CreatePage(java.lang.String,java.lang.String,java.lang.String,int,java.lang.String,int,java.lang.String)[pri:1, instance:TestAPIs.PagesAPITest@23941fb4]" started-at="2025-08-04T10:53:12 PKT" name="TC01_CreatePage" data-provider="createPageData" finished-at="2025-08-04T10:53:12 PKT" duration-ms="46" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[TestModule1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/testAuto]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ri:icon]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[26]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[error]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[400]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Path already exists]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreatePage -->
        <test-method signature="TC01_CreatePage(java.lang.String,java.lang.String,java.lang.String,int,java.lang.String,int,java.lang.String)[pri:1, instance:TestAPIs.PagesAPITest@23941fb4]" started-at="2025-08-04T10:53:12 PKT" name="TC01_CreatePage" data-provider="createPageData" finished-at="2025-08-04T10:53:12 PKT" duration-ms="59" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[TestModule1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/testAuto]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ri:icon]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[987]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[error]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[400]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Parent is not exists with given ID]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Parent is not exists with given ID] but found [Path already exists]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Parent is not exists with given ID] but found [Path already exists]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at TestAPIs.PagesAPITest.TC01_CreatePage(PagesAPITest.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreatePage -->
        <test-method signature="TC02_GetPage()[pri:2, instance:TestAPIs.PagesAPITest@23941fb4]" started-at="2025-08-04T10:53:12 PKT" name="TC02_GetPage" finished-at="2025-08-04T10:53:12 PKT" duration-ms="167" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_GetPage -->
        <test-method signature="TC03_GetPageByID()[pri:3, instance:TestAPIs.PagesAPITest@23941fb4]" started-at="2025-08-04T10:53:12 PKT" name="TC03_GetPageByID" finished-at="2025-08-04T10:53:12 PKT" duration-ms="60" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03_GetPageByID -->
        <test-method signature="TC04_DeletePageByID()[pri:4, instance:TestAPIs.PagesAPITest@23941fb4]" started-at="2025-08-04T10:53:12 PKT" name="TC04_DeletePageByID" finished-at="2025-08-04T10:53:12 PKT" duration-ms="62" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC04_DeletePageByID -->
      </class> <!-- TestAPIs.PagesAPITest -->
      <class name="TestAPIs.UsersAPITest">
        <test-method signature="TC01_CreateUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,int,java.lang.String)[pri:1, instance:TestAPIs.UsersAPITest@5d908d47]" started-at="2025-08-04T10:53:15 PKT" name="TC01_CreateUser" data-provider="createUserData" finished-at="2025-08-04T10:53:16 PKT" duration-ms="65" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[testing@m3tech.com.pk]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Testing]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Testinging]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[03215874695]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[superAdmin123@]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[Successfully Created]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Successfully Created] but found [User Already exist!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Successfully Created] but found [User Already exist!]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at TestAPIs.UsersAPITest.TC01_CreateUser(UsersAPITest.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreateUser -->
        <test-method signature="TC01_CreateUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,int,java.lang.String)[pri:1, instance:TestAPIs.UsersAPITest@5d908d47]" started-at="2025-08-04T10:53:16 PKT" name="TC01_CreateUser" data-provider="createUserData" finished-at="2025-08-04T10:53:16 PKT" duration-ms="44" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Testing]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Testinging]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[03215874695]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[superAdmin123@]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[400]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[Invalid body]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreateUser -->
        <test-method signature="TC01_CreateUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,int,java.lang.String)[pri:1, instance:TestAPIs.UsersAPITest@5d908d47]" started-at="2025-08-04T10:53:16 PKT" name="TC01_CreateUser" data-provider="createUserData" finished-at="2025-08-04T10:53:16 PKT" duration-ms="41" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[super@gamil]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Testing]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Testinging]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[03215874695]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[superAdmin123@]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[400]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[Invalid body]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreateUser -->
        <test-method signature="TC01_CreateUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,int,java.lang.String)[pri:1, instance:TestAPIs.UsersAPITest@5d908d47]" started-at="2025-08-04T10:53:16 PKT" name="TC01_CreateUser" data-provider="createUserData" finished-at="2025-08-04T10:53:16 PKT" duration-ms="165" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[testing@m3tech.com.pk]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[TestAuto_1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[TestingAuto_1]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[03215874695]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[superAdmin123@]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[400]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[email must be unique]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [0]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at TestAPIs.UsersAPITest.TC01_CreateUser(UsersAPITest.java:75)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreateUser -->
        <test-method signature="TC01_CreateUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,int,java.lang.String)[pri:1, instance:TestAPIs.UsersAPITest@5d908d47]" started-at="2025-08-04T10:53:16 PKT" name="TC01_CreateUser" data-provider="createUserData" finished-at="2025-08-04T10:53:16 PKT" duration-ms="57" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[test_1@m3tech.com.pk]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Testing]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Testinging]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[03215874695]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[superAdmin123@]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[403]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[User Already exist!]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreateUser -->
        <test-method signature="TC01_CreateUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,int,java.lang.String)[pri:1, instance:TestAPIs.UsersAPITest@5d908d47]" started-at="2025-08-04T10:53:16 PKT" name="TC01_CreateUser" data-provider="createUserData" finished-at="2025-08-04T10:53:16 PKT" duration-ms="154" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[test_1@m3tech.com.pk]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[TestAuto_1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Testinging]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[03215874695]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[superAdmin123@]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[400]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[userName must be unique]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [0]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at TestAPIs.UsersAPITest.TC01_CreateUser(UsersAPITest.java:75)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreateUser -->
        <test-method signature="TC02_GetUser()[pri:2, instance:TestAPIs.UsersAPITest@5d908d47]" started-at="2025-08-04T10:53:16 PKT" name="TC02_GetUser" finished-at="2025-08-04T10:53:16 PKT" duration-ms="107" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User not found with email: testing@m3tech.com.pk expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User not found with email: testing@m3tech.com.pk expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at TestAPIs.UsersAPITest.TC02_GetUser(UsersAPITest.java:129)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_GetUser -->
        <test-method signature="TC03_GetUserByID()[pri:3, instance:TestAPIs.UsersAPITest@5d908d47]" started-at="2025-08-04T10:53:16 PKT" name="TC03_GetUserByID" finished-at="2025-08-04T10:53:16 PKT" duration-ms="46" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "pojo.user.UserData.getEmail()" because the return value of "pojo.user.UserListDataByID.getUser()" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "pojo.user.UserData.getEmail()" because the return value of "pojo.user.UserListDataByID.getUser()" is null
at TestAPIs.UsersAPITest.TC03_GetUserByID(UsersAPITest.java:151)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03_GetUserByID -->
        <test-method signature="TC04_DeleteUserByID()[pri:4, instance:TestAPIs.UsersAPITest@5d908d47]" started-at="2025-08-04T10:53:16 PKT" name="TC04_DeleteUserByID" finished-at="2025-08-04T10:53:16 PKT" duration-ms="62" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [success] but found [error]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [success] but found [error]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at TestAPIs.UsersAPITest.TC04_DeleteUserByID(UsersAPITest.java:171)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC04_DeleteUserByID -->
      </class> <!-- TestAPIs.UsersAPITest -->
      <class name="TestAPIs.LoginTest">
        <test-method signature="testLogin(java.lang.String,java.lang.String,int,java.lang.String)[pri:0, instance:TestAPIs.LoginTest@465232e9]" started-at="2025-08-04T10:53:11 PKT" name="testLogin" data-provider="loginScenarios" finished-at="2025-08-04T10:53:11 PKT" duration-ms="169" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[superadmin@m3tech.com.pk]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[superAdmin123@]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Login Successful]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String,int,java.lang.String)[pri:0, instance:TestAPIs.LoginTest@465232e9]" started-at="2025-08-04T10:53:11 PKT" name="testLogin" data-provider="loginScenarios" finished-at="2025-08-04T10:53:11 PKT" duration-ms="175" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[superadmin@m3tech.com.pk]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[wrongpass]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[401]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Email or password is invalid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String,int,java.lang.String)[pri:0, instance:TestAPIs.LoginTest@465232e9]" started-at="2025-08-04T10:53:11 PKT" name="testLogin" data-provider="loginScenarios" finished-at="2025-08-04T10:53:11 PKT" duration-ms="47" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[superAdmin123@]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[400]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Invalid body]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String,int,java.lang.String)[pri:0, instance:TestAPIs.LoginTest@465232e9]" started-at="2025-08-04T10:53:11 PKT" name="testLogin" data-provider="loginScenarios" finished-at="2025-08-04T10:53:11 PKT" duration-ms="67" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[superadmin@m3tech.com.pk]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[400]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Invalid body]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String,int,java.lang.String)[pri:0, instance:TestAPIs.LoginTest@465232e9]" started-at="2025-08-04T10:53:11 PKT" name="testLogin" data-provider="loginScenarios" finished-at="2025-08-04T10:53:11 PKT" duration-ms="47" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[super@gamil]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[superAdmin123@]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[400]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Invalid body]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
      </class> <!-- TestAPIs.LoginTest -->
    </test> <!-- TestAPIs Sequential Execution -->
  </suite> <!-- API Test Suite -->
</testng-results>
